config/routes.rb
Rails.application.routes.draw do

  root to: 'pages#home'

  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks'
  }
  
  get 'articles/label', to: 'articles#label'
  get 'articles/lin', to: 'articles#lin'
  get 'homes/who', to: 'homes#who'
  get 'homes/contact', to: 'homes#contact'
  get 'homes/condition', to: 'homes#condition'
  get '/partners/spitzberg', to: 'partners#spitzberg'
  get 'clothes/:function/new', to: 'clothes#new', as: "new_with_function"
  get 'clothes/:function/index', to: 'clothes#index', as: "clothes_by_type"
  get 'line_items/:line_id/prev', to: 'line_items#prev', as: "prev_line"
  get 'line_items/:line_id/next', to: 'line_items#next', as: "next_line"
  get 'line_items/:line_id/up', to: 'line_items#up', as: "up_line"
  get 'line_items/:line_id/down', to: 'line_items#down', as: "down_line"


  # tuto amazon mailer
  post '/send_email', to: 'pages#send_email', as: 'send_email'


  resources :clothes do
    resources :comments, only: [ :new, :create, :edit, :update ]
    resources :line_items, only: [ :new, :create ]
    resources :scalings
    resources :dyeings
  end
  resources :orders, only: [:show, :create] do
    resources :payments, only: :new
  end

  resources :comments, only: [ :show, :destroy ]
  resources :carts, only: [ :show, :index ]
  resources :line_items, only: [ :destroy ]
  resources :delivery_adresses
  resources :dyeings
  
  resources :colors
  resources :sizes

  
  mount StripeEvent::Engine, at: '/stripe-webhooks'

end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible my-notice-style" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible my-alert-style" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<ul class="social">
  <% if current_user %>
    <% if current_user.photo.attached? %>
      <li class="my-icon"><%= cl_image_tag current_user.photo.key, height: 50, width: 50, gravity: :face, crop: :thumb, radius: 25 %></li>
    <% end %>
  <% end %>
  <li class="my-icon"><%= link_to icon('fab', 'facebook'), "https://www.facebook.com/OceNat" %></li>
  <li class="my-icon"><%= link_to icon('fab', 'instagram'), "https://www.instagram.com/ocenat.creations/?hl=fr" %></li>
</ul>

app/views/shared/_form_clothe.html.erb
<%= simple_form_for(@clothe) do |form| %>

  <% if @clothe.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@clothe.errors.count, "error") %> prohibited
        this clothe from being saved:
      </h2>
      <ul>
        <% @clothe.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= form.input :name, label: I18n.translate("clothes.form.name") %><br>

  <%= form.input :category, label: I18n.translate("clothes.form.category") %><br>

  <%= form.input :function, label: I18n.translate("clothes.form.function"), collection: ["zero", "clothing", "accessory"] %><br>

  <%= form.input :description, label: I18n.translate("clothes.form.description") %><br>

  <%= form.input :wire_type, label: "type de fil", collection: ["laine", "soie", "tissu", "coton", "lin", "bambou"] %><br>

  <p>Pour l'option, 25 caractères maximum, merci.</p>
  <%= form.input :option, label: I18n.translate("clothes.form.option") %><br>

  <%= form.input :price_cents, label: I18n.translate("clothes.form.price_cents") %><br>

  <%= form.input :delivery, label: I18n.translate("clothes.form.delivery") %><br>

  <%= form.input :delivery_color, label: I18n.translate("clothes.form.delivery_color") %><br>

  <%= form.input :stock, label: I18n.translate("clothes.form.stock") %><br>

  <%= form.input :photos, as: :file, input_html: { multiple: true }, label: I18n.translate("clothes.form.photos") %><br>

  <%= form.submit I18n.translate("clothes.form.submit"), class: "btnlink" %> | <%= link_to I18n.translate("clothes.show.back"), clothes_by_type_path(@function), class: "btnlink" %>

<% end %>

<hr>

<div class="container size-color-table">
  <table class="size-table " id="ajout">
    <thead>
      <tr>
        <th colspan="2">Tailles disponibles</th>
      </tr>
    </thead>
    <tbody>
      <% if @scalings %>
        <% @scalings.each do |scale| %>
          <tr>
            <td class="cellule-show my-table-center"><%= @sizes.where(id: scale.size_id).first.name %></td>
            <td class="cellule-show my-table-center" id="trash"><%= link_to clothe_scaling_path(@clothe.id, scale.id), method: "delete", data: { confirm: "Es tu sûre?" } do %>
              <i class="fas fa-trash-alt"></i>
            <% end %>
          </tr>
        <% end %>
      <% end %>
    </tbody>
    <tfoot>
      <tr>
        <td colspan="2" class="my-center">
          <% if @scaling %>
            <%= simple_form_for [@clothe, @scaling] do |f| %>
              <%= f.input :size_id, collection: @sizes.each { |size| [size.name, size.id] } %>
              <%= f.submit "Ajouter taille", class: "btnlink" %>
            <% end %>
          <% end %>
        </td>
      </tr>
    </tfoot>
  </table>

  <table class="color-table">
    <thead>
      <tr>
        <th colspan="2">Couleurs disponibles</th>
      </tr>
    </thead>
    <tbody>
      <% if @dyeings %>
        <% @dyeings.each do |dyeing| %>
          <tr>
            <td class="cellule-show my-table-center"><%= @colors.where(id: dyeing.color_id).first.name %></td>
            <td class="cellule-show my-table-center" id="trash"><%= link_to clothe_dyeing_path(@clothe.id, dyeing.id), method: "delete", data: { confirm: "Es tu sûre?" } do %>
              <i class="fas fa-trash-alt"></i>
            <% end %>
          </tr>
        <% end %>
      <% end %>
    </tbody>
    <tfoot>
      <tr>
        <td colspan="2" class="my-center">
          <% if @dyeing %>
            <%= simple_form_for [@clothe, @dyeing] do |f| %>
              <%= f.input :color_id, collection: @colors.each { |color| [color.name, color.id] } %>
              <%= f.submit "Ajouter couleur", class: "btnlink" %>
            <% end %>
          <% end %>
        </td>
      </tr>
    </tfoot>
  </table>

</div>

app/views/shared/_form_comment.html.erb
<%= simple_form_for [ @clothe, @comment ] do |f| %>
    <%= f.input :title, label: I18n.translate("comment.new.title") %>
    <%= f.input :content, label: I18n.translate("comment.new.content") %>
    <%= f.input :note, label: I18n.translate("comment.new.note") %>
    <%= f.submit I18n.translate("comment.new.submit"), class: "btnlink" %> | <%= link_to I18n.translate("comment.new.return"), clothe_path(@clothe.id), class: "btnlink"  %>
  <% end %>

app/views/shared/_header.html.erb
<div class="header">

  <%= link_to image_tag("logo.png", class: "logo"), root_path %>

  <h1 class="my-title">
    <p class="oce">Oce</p>
    <p class="nat">Nat</p>
    <p class="creations">Creations</p>
  </h1>

  <div id="cubic" class="restrict">
    <%= image_tag("myburger.png", size: "46x46", alt: "Burger img", id: "burger")%>
    <%= image_tag("mycross.png", size: "46x46", alt: "Cross img", id: "cross")%>
  </div>
  
</div>

<div id="menu" class="menuup">
  <p>Connection <i id="connection" class="fas fa-angle-left"></i></p><br>
  <div id="connectionMenu">
    <% if current_user %>
        <%= link_to I18n.translate("shared.header.signout"), destroy_user_session_path, method: "delete", data: {confirm: 'Etes vous sûr de vouloir vous déconnecter?'}, class: "btnlink" %><br>
        <%= link_to "Editer mon profil", edit_user_registration_path, class: "btnlink" %>
    <% else %>
      <%= link_to I18n.translate("shared.header.signin"), new_user_session_path, class: "btnlink" %><br>
      <%= link_to I18n.translate("shared.header.forgot"),  new_user_password_path, class: "btnlink" %>
    <% end %>
  </div><hr>
  <p>Langue <i id="language" class="fas fa-angle-left"></i></p><br>
  <div id="langue">
    <label id="labelLangue"><%= @langue %></label>
    <button id="francais"><%= link_to "Français", url_for(only_path: true, locale: "fr") %></button>
    <button id="english"><%= link_to "English", url_for(only_path: true, locale: "en") %></button>
    <button id="espanol"><%= link_to "Espanol", url_for(only_path: true, locale: "es") %></button>
  </div><hr>
  <p>Panier <i id="cart" class="fas fa-angle-left"></i></p><br>
  <div class="my-cart" id="cartMenu">
    <% if @all_line_items %>
      <%= I18n.translate("shared.header.you_have", count: @total_count) %><br>
      <%= link_to I18n.translate("shared.header.see_cart"), cart_path(current_user.cart.id), class: "btnlink" %>
    <% end %>
  </div><hr>
</div>