config/routes.rb
Rails.application.routes.draw do

  root to: 'pages#home'

  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks'
  }
  
  get 'articles/label', to: 'articles#label'
  get 'articles/lin', to: 'articles#lin'
  get 'homes/who', to: 'homes#who'
  get 'homes/contact', to: 'homes#contact'
  get 'homes/condition', to: 'homes#condition'
  get '/partners/spitzberg', to: 'partners#spitzberg'
  get 'clothes/:function/new', to: 'clothes#new', as: "new_with_function"
  get 'clothes/:function/index', to: 'clothes#index', as: "clothes_by_type"
  get 'line_items/:line_id/prev', to: 'line_items#prev', as: "prev_line"
  get 'line_items/:line_id/next', to: 'line_items#next', as: "next_line"
  get 'line_items/:line_id/up', to: 'line_items#up', as: "up_line"
  get 'line_items/:line_id/down', to: 'line_items#down', as: "down_line"


  # tuto amazon mailer
  post '/send_email', to: 'pages#send_email', as: 'send_email'


  resources :clothes do
    resources :comments, only: [ :new, :create, :edit, :update ]
    resources :line_items, only: [ :new, :create ]
    resources :scalings
    resources :dyeings
  end
  resources :orders, only: [:show, :create] do
    resources :payments, only: :new
  end

  resources :comments, only: [ :show, :destroy ]
  resources :carts, only: [ :show, :index ]
  resources :line_items, only: [ :destroy ]
  resources :delivery_adresses
  resources :dyeings
  
  resources :colors
  resources :sizes

  
  mount StripeEvent::Engine, at: '/stripe-webhooks'

end

app/models/clothe.rb
class Clothe < ApplicationRecord
  has_many_attached :photos
  has_many :comments, dependent: :destroy
  has_many :line_items
  has_many :dyeings, dependent: :destroy
  has_many :scalings, dependent: :destroy
  has_many :colors, through: :dyeings
  has_many :sizes, through: :scalings

  translates :name, :description, :category, :delivery, :option

  monetize :price_cents

  validates :name, presence: true
  validates :category, presence: true
  validates :price_cents, presence: true
  validates :stock, presence: true
end

app/controllers/clothes_controller.rb
class ClothesController < ApplicationController
  require 'uri'
  require 'net/http'
  require 'openssl'

  skip_before_action :authenticate_user!, only: [:index], unless: :skip_pundit?
  skip_after_action :verify_authorized, only: [:index], unless: :skip_pundit?
  before_action :function_params, only: %i[index new destroy]

  def index
    @search = params["search"]
    if @search.present?
      @clothes = policy_scope(Clothe).all.select { |clothe| clothe.name.downcase.include? @search[:name].downcase }
      unless @clothes.first
        @clothes = policy_scope(Clothe).order(created_at: :desc).includes([:photos_attachments])
        redirect_to clothes_by_type_path(@function), notice: I18n.translate("clothes.index.nothing")
      end
    else
      @clothes = policy_scope(Clothe).where(function: @function).order(created_at: :desc).includes([:photos_attachments]).includes([:translations])
    end
  end

  def show
    @line_item = LineItem.new
    @clothe = Clothe.find(params[:id])
    if current_user && Cart.where(user_id: current_user.id).where(state: "panier").last.nil?
      cart = Cart.create!(state: "panier", user_id: current_user.id)
      current_user.update(cart_id: cart.id)
    end
    @comments = Comment.where(clothe_id: @clothe.id).includes(:user)
    authorize @clothe
    authorize @comments
  end

  def new
    @clothe = Clothe.new
    authorize @clothe
  end

  def create
    I18n.locale = :fr
    @clothe = Clothe.new(clothe_params)
    @clothe.scoring = 5
    @clothe.nbov = 0
    @clothe.save!

    TraductionService.trad(@clothe, @clothe.name, @clothe.description, @clothe.category, @clothe.delivery, @clothe.option, "en")
    TraductionService.trad(@clothe, @clothe.name, @clothe.description, @clothe.category, @clothe.delivery, @clothe.option, "es")

    authorize @clothe
    if @clothe.save
      redirect_to @clothe
    else
      render 'new'
    end
  end

  def edit
    @clothe = Clothe.find(params[:id])
    @sizes = Size.all
    @scalings = Scaling.where(clothe_id: @clothe.id)
    @scaling = Scaling.new
    @colors = Color.all
    @dyeings = Dyeing.where(clothe_id: @clothe.id)
    @dyeing = Dyeing.new
    authorize @clothe
  end

  def update
    @clothe = Clothe.find(params[:id])
    I18n.locale = :fr
    @clothe.update(clothe_params)

    TraductionService.trad(@clothe, @clothe.name, @clothe.description, @clothe.category, @clothe.delivery, @clothe.option, "en")
    TraductionService.trad(@clothe, @clothe.name, @clothe.description, @clothe.category, @clothe.delivery, @clothe.option, "es")

    authorize @clothe
    if @clothe.persisted?
      redirect_to @clothe
    else
      render 'edit'
    end
  end

  def destroy
    @clothe = Clothe.find(params[:id])
    authorize @clothe
    @clothe.destroy
    redirect_to clothes_path
  end

  private

  def clothe_params
    params.require(:clothe).permit(:name, :function, :category, :description, :wire_type, :option, :price_cents, :scoring, :nbov, :delivery, :delivery_color, :stock, photos: [])
  end

  def function_params
    @function = params[:function]
  end
end

app/views/clothes/edit.html.erb
<div id="editmain">

  <h1 id="clothe-edit-title">
    <%= I18n.translate("clothes.edit.update") %><br>
    <%= @clothe.name %>
  </h1>
  <div class="container">
    <%= render 'shared/form_clothe' %>
  </div>

</div>

app/views/clothes/index.html.erb
<h1 class="indexclothetitle"><%= I18n.translate("clothes.index.title.#{@function}") %></h1>

<div class="index-clothes-page">

  <div class="search-bar-container container">
    <p class="slogan"><%= I18n.translate("clothes.index.slogan") %></p>
    <%= simple_form_for :search, url: clothes_by_type_path(@function), method: "GET", html: { class: 'form-inline search-tool' } do |f| %>
      <%= f.input :name, label: "", input_html: {value: "", placeholder: I18n.translate("clothes.index.search") } %>
      <%= f.submit ' ', class: "btn", id: "my-search-button" %>
      <i class="fas fa-search" id="magnify-icon"></i>
    <% end %>
  </div>

  <p id="notice"><%= notice %></p>
  <p id="alert"><%= alert %></p>

  <main>
    <div id="card" class="container">
        <% @clothes.each do |clothe| %>
          <div class="each-card">
            <div class="card1 overflow">
              <% if clothe.photos[0] %>
                <%= cl_image_tag clothe.photos[0].key, width: 400, height: 300, class: "clothe_index_image", crop: :fill %>
              <% end %>
              <%= content_tag(:p, clothe.option, id: "option#{clothe.id}", class: "option" ) %>
            </div>
            <div class="card2 overflow">
              <div class="description">
                <h2><%= clothe.name %></h2>

                <p>
                  <p><%= I18n.translate("clothes.index.price") %> <strong><%= humanized_money_with_symbol(clothe.price) %></strong></p>
                </p>

                <p>
                  <p><%= I18n.translate("clothes.index.note") %> </p>
                  <%= content_tag(:p,"", id: "displaystars#{clothe.id}", class: "displaystars" ) %>
                  <p><%= I18n.translate("clothes.index.ononon", count: clothe.nbov) %></p>
                </p>

                <p>
                  <p><%= I18n.translate("clothes.index.delivery") %> </p>
                  <%= content_tag(:strong, id: "delivery#{clothe.id}", class: "delivery") do %>
                    <%= clothe.delivery %>
                  <% end %>
                </p>

                <%= content_tag(:p, clothe.delivery_color, id: "indexColor#{clothe.id}", class: "indexColor" ) %>
                <%= content_tag(:p, clothe.scoring, id: "slide#{clothe.id}", class: "slide" ) %>

                <%= link_to I18n.translate("clothes.index.see"), clothe_path(clothe.id), class: "btnlink" %>
                <% if policy(Clothe).edit? %>
                  <%= link_to I18n.translate("clothes.index.edit"), edit_clothe_path(clothe.id), class: "btnlink" %>
                <% end %>
                <% if policy(Clothe).destroy? %>
                  <%= link_to I18n.translate("clothes.index.delete"), clothe_path(clothe), method: "delete", data: {confirm: 'Etes vous sûr?'}, class: "btnlink" %>
                <% end %>
              </div>
            </div>
          </div>
        <% end %>
      </div>
  </main>

  <hr>

  <% if policy(Clothe).new? %>
    <%= link_to I18n.translate("clothes.index.newclothe"), new_with_function_path(@function), class: "btnlink" %>
  <% end %>

  <% if policy(Cart).index? %>
    <%= link_to "voir toutes les commandes", carts_path, class: "btnlink" %>
  <% end %>

</div>

app/views/clothes/new.html.erb
<div id="newmain">

  <h1 id="clothe-new-title">
    <%= I18n.translate("clothes.new.title") %><br>
  </h1>
  <div class="container">
    <%= render 'shared/form_clothe' %>
  </div>

</div>

app/views/clothes/show.html.erb
<div id="showmain">
  <h1 class="showTitle"><%= @clothe.name %></h1>
  <div id="showContainerRow">
    <div id="showLeftPart">
      <div class="my-viewer">
        <p id="right-button"><i class="fas fa-arrow-circle-left"></i></p>
          <% @clothe.photos.each_with_index do |photo, index| %>
            <div class="overflow_option">
              <%= cl_image_tag photo.key, id:"photo#{index}", class:"picture", width: 800, height:500, crop: :fill %>
              <%= content_tag(:p, @clothe.option, id: "option#{@clothe.id}", class: "option-show" ) %>
            </div>
          <% end %>
        <p id="left-button"><i class="fas fa-arrow-circle-right"></i></p>
      </div>
      
      <div class="my-little-picture">
        <% count = 0 %>
        <% @clothe.photos.each do |photo| %>
          <%= cl_image_tag photo.key, id: "miniature#{count}", class: "miniature", height: 60, width: 60, crop: :fill %>
          <% count += 1 %>
        <% end %>
      </div>
    </div>

    <div class="container">
      <p><%= @clothe.description %></p>
      <div class="container">
        <%= I18n.translate("clothes.index.note") %>
        <%= content_tag(:p,"", id: "displaystars#{@clothe.id}", class: "displaystars" ) %>
        <p><%= I18n.translate("clothes.index.ononon", count: @clothe.nbov) %></p>
      </div>
      <div id="showRightPart">
        <p>Prix: <%= humanized_money_with_symbol(@clothe.price) %></p>
        <%= I18n.translate("clothes.index.delivery") %>
        <%= content_tag(:strong, id: "delivery#{@clothe.id}", class: "delivery") do %>
          <%= @clothe.delivery %>
        <% end %>
        <%= content_tag(:p, @clothe.delivery_color, id: "indexColor#{@clothe.id}", class: "indexColor") %>
        <%= content_tag(:p, @clothe.scoring, id: "slide#{@clothe.id}", class: "slide") %>
      </div>

      <%# ajout du formulaire de choix de taille et couleur qui creer line item %>

        <%= simple_form_for [ @clothe, @line_item ] do |f| %>
          <% if current_user %>
            <%= f.hidden_field :cart_id, value: current_user.cart_id %>
            <%= f.hidden_field :clothe_id, value: @clothe.id %>
            <%= f.hidden_field :quantity, value: 1 %>
            <%= f.hidden_field :state, value: "panier" %>
            <% if @clothe.function == "clothing" %>
              <div class="option-choice">
                <%= f.input :color, label: I18n.translate("clothes.show.color"), collection: @clothe.colors.each { |color| [color.name, color.id] } %>
                <%= f.input :size, label: I18n.translate("clothes.show.size"), collection: @clothe.sizes.each { |size| [size.name, size.id] } %>
              </div>
            <% end %>
          <% end %>
          <div class="text-center">
            <%= f.submit I18n.translate("clothes.show.basket"), class: "btnlink" %>
          </div>
        <% end %><br>




      <div id="links">
        <% if policy(Clothe).edit? %>
          <%= link_to I18n.translate("clothes.show.edit"), edit_clothe_path(@clothe), class: "btnlink" %>
        <% end %>
        <%= link_to I18n.translate("clothes.show.back"), clothes_by_type_path(@clothe.function), class: "btnlink" %>
        <%= content_tag(:button, I18n.translate("clothes.show.comments"), id: "displayComment", class: "btnlink") %>
        
        <% if @clothe.function == "clothing" %>
          <%= content_tag(:button, I18n.translate("clothes.show.size"), id: "displaySize", class: "btnlink") %>
        <% end %>
      </div>
    </div>
  </div>
</div>
<hr>

<div class="container hidden-options" id="set-size">
  <h2><%= I18n.translate("clothes.size.title") %></h2>
  <p><%= I18n.translate("clothes.size.texte") %></p>
  <div class="container centrage-size">
    <img src="https://res.cloudinary.com/do3nu0tns/image/upload/v1597264819/avk3am6sd9mflqzvb0vb.png" alt=<%= I18n.translate("clothes.size.alt") %> class="mannequin">
    <div class="container my-legende">
      <p><strong><%= I18n.translate("clothes.size.strong1") %></strong><%= I18n.translate("clothes.size.texte1") %></p>
      <p><strong><%= I18n.translate("clothes.size.strong2") %></strong><%= I18n.translate("clothes.size.texte2") %></p>
      <p><strong><%= I18n.translate("clothes.size.strong3") %></strong><%= I18n.translate("clothes.size.texte3") %></p>
      <p><strong><%= I18n.translate("clothes.size.strong4") %></strong><%= I18n.translate("clothes.size.texte4") %></p>
      <p><strong><%= I18n.translate("clothes.size.strong5") %></strong><%= I18n.translate("clothes.size.texte5") %></p>
      <p><strong><%= I18n.translate("clothes.size.strong6") %></strong><%= I18n.translate("clothes.size.texte6") %></p>
    </div>
  </div>
  
  <p class="title-size"><%= I18n.translate("clothes.size.mensuration") %></p>
  <div id="size-tableau">
      <table id="mesures">
        <tbody>
          <tr class="row-size">
            <td colspan="2"><%= I18n.translate("clothes.size.stature") %></td>
            <% (160..185).to_a.each do |stature| %>
              <td class="cellule-size"><%= stature %></td>
            <% end %>
          </tr>
          <tr class="row-size">
            <td colspan="2"><%= I18n.translate("clothes.size.poitrine") %></td>
            <% (74..124).to_a.each do |poitrine| %>
              <% if poitrine.even? %>
                <td class="cellule-size"><%= poitrine %></td>
              <% end %>
            <% end %>
          </tr>
          <tr class="row-size">
            <td colspan="2"><%= I18n.translate("clothes.size.taille") %></td>
            <% (58..108).to_a.each do |taille| %>
              <% if taille.even? %>
                <td class="cellule-size"><%= taille %></td>
              <% end %>
            <% end %>
          </tr>
          <tr class="row-size">
            <td colspan="2"><%= I18n.translate("clothes.size.hanche") %></td>
            <% (80..130).to_a.each do |hanches| %>
              <% if hanches.even? %>
                <td class="cellule-size"><%= hanches %></td>
              <% end %>
            <% end %>
          </tr>
          <tr class="row-size">
            <td colspan="2"><%= I18n.translate("clothes.size.bras") %></td>
            <% (57..65).to_a.each do |bras| %>
              <td class="cellule-size"><%= bras %></td>
            <% end %>
            <% 17.times do %>
              <td class="cellule-size"></td>
            <% end %>
          </tr>
          <tr class="row-size">
            <td colspan="2"><%= I18n.translate("clothes.size.epaule") %></td>
            <% (110..155).to_a.each do |epaule| %>
              <% if epaule%5 == 0 %>
                <td class="cellule-size"><%= epaule/10 %></td>
              <% end %>
            <% end %>
            <% 16.times do %>
              <td class="cellule-size"></td>
            <% end %>
          </tr>
        </tbody>
        <tfoot>
          <tr>
            <td colspan="28"><%= I18n.translate("clothes.size.legende") %></td>
          </tr>
        </tfoot>
    </table>
  </div>
</div>

<hr>

<div class="container">
  <div id="all-comments" class="hidden-options">
    <% @comments.each do |comment| %>
      <div class="each-comment">
        <% if comment.user.photo.present?%>
          <div class="my-avatar" style="background-image: url('<%= cl_image_path comment.user.photo.key, height: 50, width: 50, crop: :thumb, gravity: :face %>')"></div>
        <% end %>
        <div>
          <% if comment.title.length > 32 %>
            <p class="comment-title"><%= comment.title[0..32] %>...</p>
          <% else %>
            <p class="comment-title"><%= comment.title %></p><br>
          <% end %>
        </div>
        <div>
          <% if comment.content.length > 100 %>
            <p><%= comment.content[0..100] %>...</p>
          <% else %>
            <%= comment.content %><br>
          <% end %>
          <p class="author"><%= comment.user.username %></p><br>
        </div>
        <div class="comment-links">
            <%= link_to I18n.translate("comment.links.see"), comment_path(comment), class: "btnlink" %>
          <% if policy(comment).destroy? %>      
            <%= link_to I18n.translate("comment.links.remove"),
                        comment_path(comment),
                        method: :delete,
                        data: { confirm: "Are you sure?" },
                        class: "btnlink" %>
          <% end %>
          <% if policy(comment).edit? %>  
            <%= link_to I18n.translate("comment.links.update"), edit_clothe_comment_path(@clothe, comment), class: "btnlink" %>
          <% end %>
        </div>
      </div>
      <hr>
    <% end %>
    <% if policy(Comment).new? %>
      <%= link_to I18n.translate("clothes.show.comment"), new_clothe_comment_path(@clothe), class: "btnlink" %>
    <% end %>
  </div>
</div>
<hr>