config/routes.rb
Rails.application.routes.draw do

  root to: 'pages#home'

  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks'
  }
  
  get 'articles/label', to: 'articles#label'
  get 'articles/lin', to: 'articles#lin'
  get 'homes/who', to: 'homes#who'
  get 'homes/contact', to: 'homes#contact'
  get 'homes/condition', to: 'homes#condition'
  get '/partners/spitzberg', to: 'partners#spitzberg'
  get 'clothes/:function/new', to: 'clothes#new', as: "new_with_function"
  get 'clothes/:function/index', to: 'clothes#index', as: "clothes_by_type"
  get 'line_items/:line_id/prev', to: 'line_items#prev', as: "prev_line"
  get 'line_items/:line_id/next', to: 'line_items#next', as: "next_line"
  get 'line_items/:line_id/up', to: 'line_items#up', as: "up_line"
  get 'line_items/:line_id/down', to: 'line_items#down', as: "down_line"


  # tuto amazon mailer
  post '/send_email', to: 'pages#send_email', as: 'send_email'


  resources :clothes do
    resources :comments, only: [ :new, :create, :edit, :update ]
    resources :line_items, only: [ :new, :create ]
    resources :scalings
    resources :dyeings
  end
  resources :orders, only: [:show, :create] do
    resources :payments, only: :new
  end

  resources :comments, only: [ :show, :destroy ]
  resources :carts, only: [ :show, :index ]
  resources :line_items, only: [ :destroy ]
  resources :delivery_adresses
  resources :dyeings
  
  resources :colors
  resources :sizes

  
  mount StripeEvent::Engine, at: '/stripe-webhooks'

end

app/models/cart.rb
class Cart < ApplicationRecord
  has_one :order
  has_many :line_items

  monetize :price_cents

  validates :state, inclusion: { in: ["panier", "payé", "réalisation", "réalisé", "envoi", "cloturé"],
                                 message: "%<value> is not a valid state" }
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def index
    @line_items = LineItem.all.order(id: :desc).includes([:clothe])
    @carts = policy_scope(Cart).where.not(order_id: nil).order(id: :desc)
    authorize @line_items
    authorize @carts
  end

  def show
    @cart = Cart.where(user_id: current_user.id).where(state: "panier").last
    @all_line_items = LineItem.where(cart_id: @cart.id).includes(:clothe).order(id: :desc)
    @total_price = 0
    @all_line_items.each do |line|
      @total_price += (line.quantity * (line.clothe.price_cents/100))
    end
    @cart.price_cents = @total_price*100
    current_user.cart.price_cents = @total_price
    @cart.save!
    authorize @cart
  end
end

app/views/carts/index.html.erb
<h1 id="cart-index-title">Paniers en cours</h1>
<div class="container total-space">
  <% @carts.each do |cart| %>
    <% if @line_items.where(cart_id: cart.id).first %>
      <div class="my-informations">
        <div class="info-left">
          <p>Le client: <%= User.find(cart.user_id).username %></p>
          <p>A commandé le: <%= Order.find(cart.order_id).created_at.to_date %></p>
          <p>Cette commande est actuellement: </p><span class="state-target"><%= cart.state %></span>
        </div>
        <div class="info-right">
          <p>Envoyer cette commande à: </p>
          <% adress = DeliveryAdress.find(User.find(cart.user_id).delivery_adress_id) %>
          <p class="name"><%= adress.first_name %> <%= adress.last_name %></p><p>, tel: <%= adress.phone_number %></p>
          <p class="adress"><%= adress.adress1 %>, <%= adress.adress2 %></p>
          <p class="zip-city"><%= adress.zipcode %> <%= adress.city %>, <%= adress.state %></p>
          <% if adress.delivery_instructions != "" %>
            <p class="instructions"><%= adress.delivery_instructions %></p>
          <% end %>
          <% if adress.code_secure != "" %>
            <p >Digicode: <span class="code"><%= adress.code_secure %></span></p>
          <% end %>
        </div>
      </div>
      <table class="comptability-table">
          <thead>
              <tr>
                  <th>N°</th>
                  <th>Vetement</th>
                  <th>Quantité</th>
                  <th>Couleur</th>
                  <th>Taille</th>
                  <th>Prev</th>
                  <th>Etat</th>
                  <th>Next</th>
              </tr>
          </thead>
          <tbody>
            <tr class="row-min-height">
                <td class="cellule-show"></td>
                <td class="cellule-show"></td>
                <td class="cellule-show"></td>
                <td class="cellule-show"></td>
                <td class="cellule-show"></td>
                <td class="cellule-show"></td>
                <td class="cellule-show"></td>
                <td class="cellule-show"></td>
              </tr>
            <% @line_items.where(cart_id: cart.id).each do |line_item| %>
              <tr>
                <td class="cellule-show"><%= line_item.id %></td>
                <td class="cellule-show my-table-center"><%= line_item.clothe.name %></td>
                <td class="cellule-show my-table-center"><%= line_item.quantity %></td>
                <% if line_item.color %>
                  <td class="cellule-show my-table-center"><%= Color.find(line_item.color).name %></td>
                <% else %>
                  <td class="cellule-show my-table-center"></td>
                <% end %>
                <% if line_item.size %>
                  <td class="cellule-show my-table-center"><%= Size.find(line_item.size).name %></td>
                <% else %>
                  <td class="cellule-show my-table-center"></td>
                <% end %>
                <td class="cellule-show my-table-center"><%= link_to prev_line_path(line_item.id) do %>
                  <i class="fas fa-step-backward"></i>
                <% end %>
                <td class="cellule-show my-table-center state-target"><%= line_item.state %></td>
                <td class="cellule-show my-table-center"><%= link_to next_line_path(line_item.id) do %>
                  <i class="fas fa-step-forward"></i>
                <% end %>
                </td>
              </tr>
            <% end %>
          </tbody>
          <tfoot>
          <tr>
            <td colspan="8"></td>
          </tr>
        </tfoot>
      </table>
    <% end %>
  <% end %>

  <button id="make" class="btnlink">Générer les étiquettes</button>


</div>

  

app/views/carts/show.html.erb
<h1 id="cart-show-title"><%= I18n.translate("cart.show.title") %></h1>
<div class="container total-space">
  <table>
      <thead>
          <tr>
              <th><%= I18n.translate("cart.show.article") %></th>
              <th>Up</th>
              <th><%= I18n.translate("cart.show.quantity") %></th>
              <th>Down</th>
              <th class="hidden-phone"><%= I18n.translate("cart.show.color") %></th>
              <th class="hidden-phone"><%= I18n.translate("cart.show.size") %></th>
              <th><%= I18n.translate("cart.show.price") %></th>
              <th><%= I18n.translate("cart.show.total_price") %></th>
              <th><%= I18n.translate("cart.show.delete") %></th>
          </tr>
      </thead>
      <tbody>
        <tr class="row-min-height">
            <td class="cellule-show"></td>
            <td class="cellule-show"></td>
            <td class="cellule-show"></td>
            <td class="cellule-show"></td>
            <td class="cellule-show hidden-phone"></td>
            <td class="cellule-show hidden-phone"></td>
            <td class="cellule-show"></td>
            <td class="cellule-show"></td>
            <td class="cellule-show"></td>
          </tr>
        <% @all_line_items.each do |line_item| %>
          <tr>
            <td class="cellule-show"><%= line_item.clothe.name %></td>
            <td class="cellule-show my-table-center"><%= link_to down_line_path(line_item.id) do %>
              <i class="fas fa-sort-down"></i>
            <% end %>
            <td class="cellule-show my-table-center"><%= line_item.quantity %></td>
            <td class="cellule-show my-table-center"><%= link_to up_line_path(line_item.id) do %>
              <i class="fas fa-caret-up"></i>
            <% end %>
            <% if line_item.color %>
              <td class="cellule-show my-table-center hidden-phone"><%= (Color.find(line_item.color)).name %></td>
            <% else %>
              <td class="cellule-show my-table-center hidden-phone"></td>
            <% end %>
            <% if line_item.size %>
              <td class="cellule-show my-table-center hidden-phone"><%= (Size.find(line_item.size)).name %></td>
            <% else %>
              <td class="cellule-show my-table-center hidden-phone"></td>
            <% end %>
            <td class="cellule-show"><%= "#{line_item.clothe.price_cents/100}.00 Euros." %></td>
            <td class="row-total cellule-show"><%= "#{line_item.quantity * (line_item.clothe.price_cents/100)}.00 Euros." %></td>
            <td class="cellule-show my-table-center" id="trash"><%= link_to line_item_path(line_item.id), method: "delete", data: { confirm: I18n.translate("cart.show.really") } do %>
              <i class="fas fa-trash-alt"></i>
            <% end %>
            </td>
          </tr>
        <% end %>
      </tbody>
      <tfoot>
      <tr>
        <td colspan="5"><%= I18n.translate("cart.show.main_total") %></td>
        <td colspan="2" class="hidden-phone"></td>
        <td id="main-total"><%= @total_price %>.00 Euros.</td>
        <td></td>
      </tr>
    </tfoot>
  </table>
</div>
<br>
<div class="container">
  <p><%= I18n.translate("cart.show.amount") %><%= humanized_money_with_symbol(current_user.cart.price_cents) %>.00</p>
  
  <% if @total_price > 0 %>
    <%= link_to I18n.translate("cart.show.commande"), new_delivery_adress_path, class: "btnlink" %>
  <% end %>

  <%= link_to I18n.translate("cart.show.return"), clothes_by_type_path("clothing"), class: "btnlink" %>
</div>