config/routes.rb
Rails.application.routes.draw do

  root to: 'pages#home'

  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks'
  }
  
  get 'articles/label', to: 'articles#label'
  get 'articles/lin', to: 'articles#lin'
  get 'homes/who', to: 'homes#who'
  get 'homes/contact', to: 'homes#contact'
  get 'homes/condition', to: 'homes#condition'
  get '/partners/spitzberg', to: 'partners#spitzberg'
  get 'clothes/:function/new', to: 'clothes#new', as: "new_with_function"
  get 'clothes/:function/index', to: 'clothes#index', as: "clothes_by_type"
  get 'line_items/:line_id/prev', to: 'line_items#prev', as: "prev_line"
  get 'line_items/:line_id/next', to: 'line_items#next', as: "next_line"
  get 'line_items/:line_id/up', to: 'line_items#up', as: "up_line"
  get 'line_items/:line_id/down', to: 'line_items#down', as: "down_line"


  # tuto amazon mailer
  post '/send_email', to: 'pages#send_email', as: 'send_email'


  resources :clothes do
    resources :comments, only: [ :new, :create, :edit, :update ]
    resources :line_items, only: [ :new, :create ]
    resources :scalings
    resources :dyeings
  end
  resources :orders, only: [:show, :create] do
    resources :payments, only: :new
  end

  resources :comments, only: [ :show, :destroy ]
  resources :carts, only: [ :show, :index ]
  resources :line_items, only: [ :destroy ]
  resources :delivery_adresses
  resources :dyeings
  
  resources :colors
  resources :sizes

  
  mount StripeEvent::Engine, at: '/stripe-webhooks'

end

app/controllers/delivery_adresses_controller.rb
class DeliveryAdressesController < ApplicationController
  def new
    @delivery_adress = DeliveryAdress.new
    authorize @delivery_adress
  end

  def create
    @delivery_adress = DeliveryAdress.new(params_delivery_adress)
    @delivery_adress.save!
    @user = current_user
    @user.delivery_adress_id = @delivery_adress.id
    @user.save!
    authorize @delivery_adress
  end

  private

  def params_delivery_adress
    params.require(:delivery_adress).permit(:first_name, :last_name, :adress1, :adress2, :city,
                                            :state, :zipcode, :phone_number, :delivery_instructions, :code_secure)
  end
end

app/views/delivery_adresses/new.html.erb
<h1>Delivery Adresses</h1>

<%= simple_form_for @delivery_adress do |f| %>
  <%= f.input :first_name %>
  <%= f.input :last_name %>
  <%= f.input :adress1 %>
  <%= f.input :adress2 %>
  <%= f.input :city %>
  <%= f.input :state %>
  <%= f.input :zipcode %>
  <%= f.input :phone_number %>
  <%= f.input :delivery_instructions %>
  <%= f.input :code_secure %>
  <%= f.button :submit, label:"Valider mon adresse" %>
<% end %>

<%= form_tag orders_path do %>
  <%= hidden_field_tag 'cart_id', current_user.cart.id %>
  <%= submit_tag 'Régler ma commande', class: 'btnlink' %>
<% end %>